version: '3.6'

services:
  web-application:
    build: ./application
    ports:
      - 4000:4000
    volumes: 
      - ./application/src:/application/src
    depends_on:
      - ms-db
      - mongo-db
  ms-db:
    build: ./mysql
    platform: linux/amd64
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: ms-db
      MYSQL_ROOT_PASSWORD: root
  mongo-db:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: testarn         # name
      MONGO_INITDB_ROOT_USERNAME: root       # username 
      MONGO_INITDB_ROOT_PASSWORD: root       # password
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017:27017'
    command: --quiet --logpath /dev/null 
    