version: '3.6'

services:
  web-application:
    build: ./application
    ports:
      - 4000:4000
    volumes: 
      - ./application/src:/application/src
  ms-db:
    build: ./mysql
    platform: linux/amd64
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: ms-db
      MYSQL_ROOT_PASSWORD: root
    